### ISSUE TITLE
hi,thanks for your work, but mAp is too bad,   how can i improve the result?

### ISSUE THREAD

**Issue by aa12356jm** [eric612/Caffe-YOLOv2-Windows#1]

**Comment by eric612** [comment]
I got same problem with [issue](https://github.com/choasUp/caffe-yolo9000/issues/8) 
The region loss output are same as [caffe](https://github.com/unsky/yolo-for-windows-v2) , so I guess is data augmentation problem, where the original project has jitter,random size,image distortion.
