### ISSUE TITLE
map  57.9 on voc2007test

### ISSUE THREAD

**Issue by zlheos** [eric612/Caffe-YOLOv2-Windows#11]
I test voc2007 with mobilenet_yolov3_lite_deploy
but the map has only 57.9
I don't know why?

**Comment by eric612** [comment]
Here was my evaluation log on linux version 
[eval-2018-10-12-10-49-38.log](https://github.com/eric612/Caffe-YOLOv3-Windows/files/2471402/eval-2018-10-12-10-49-38.log)
