### ISSUE TITLE
How do i  transform image data to lmdb  on windows

### ISSUE THREAD

**Issue by zhangcj13** [eric612/Caffe-YOLOv2-Windows#14]
hello:
    I want to train my own yolov3 model, I do't know how to get the lmdb data. 
    In caffe, it has converts_imageset, but I doubt it may not be suitable  for yolo3 or ssd train data.
   So How do i  transform image data to lmdb  on windows

**Comment by wenhaopeter** [comment]
I want to know that.

**Comment by wenhaopeter** [comment]
can i use convert_annoset.exe directly to convert data?

**Comment by eric612** [comment]
Currently , it can't produce lmdb from this project . but @wenhaopeter  is right , you can write a cmd script and then call conver_annoset.exe , just like create_list.sh and create_data.sh

**Comment by wenhaopeter** [comment]
I have successfully converted the data. When i train the net using the "examples\train_yolov3_lite.cmd"(i changed the weight=mobilenet_yolov3_lite_deploy_iter_50000.caffemodel) , i have the problem about  the value of mAP is always zero,and appearing "Missing true_pos for label" but the loss has been reduced .what is the problem ? I want to get the value of mAP.

**Comment by wenhaopeter** [comment]
@eric612

**Comment by wenhaopeter** [comment]
sorry, I had a problem with my script,and my problem has been solved.

**Comment by zhangcj13** [comment]
@eric612  thx，“using create_annoset to make a windows bat file”  this method can make lmdb data on widows
