### ISSUE TITLE
question about platform

### ISSUE THREAD

**Issue by CBIR-LL** [eric612/Caffe-YOLOv2-Windows#2]
Can I switch to Linux platform training and using?

**Comment by HKLee2040** [comment]
You will meet following error message:

src/caffe/util/io.cpp: In function ‘bool caffe::ReadProtoFromBinaryFile(const char*, google::protobuf::Message*)’:
src/caffe/util/io.cpp:62:36: error: ‘O_BINARY’ was not declared in this scope
   int fd = open(filename, O_RDONLY|O_BINARY);
                                    ^
Makefile:572: recipe for target '.build_release/src/caffe/util/io.o' failed
make: *** [.build_release/src/caffe/util/io.o] Error 1

In Linux, O_BINARY is not defined!

**Comment by ersanliqiao** [comment]
In Linux, you should change line to below:
int fd = open(filename, O_RDONLY);

**Comment by 0-LL-0** [comment]
@HKLee2040 @ersanliqiao Thanks for your help. I will try your opinion.
