### ISSUE TITLE
MobileNetYolo_deploy.caffemodel

### ISSUE THREAD

**Issue by DanielXu123** [eric612/Caffe-YOLOv2-Windows#3]
Hi, Eric.

It's me, Daniel. Again :) 

Would you pls update the MobileNetYolo_deploy.caffemodel file to github?
Or is it hidden in somewhere that I can't find it. 

Cheers

**Comment by eric612** [comment]
I replace the ssd loss layer to yolo_v2_loss_layer at my mobilenet-SSD project and it's works fine
https://github.com/eric612/MobileNet-SSD-linux
