### ISSUE TITLE
The convert tools doesn't seem to work

### ISSUE THREAD

**Issue by HKLee2040** [eric612/Caffe-YOLOv2-Windows#4]
The convert tools doesn't seem to work.
$ python create_yolo_prototxt.py yolov2.cfg yolov2.prototxt

ERROR:root:route layer is not supported
ERROR:root:reorg layer is not supported
ERROR:root:route layer is not supported
ERROR:root:region layer is not supported

**Comment by HKLee2040** [comment]
I saw there is reorg_layer in this package.  Can you share the yolo prototxt example that uses reorg_layer?

**Comment by eric612** [comment]
I only try my tiny-yolo (yolov2) success , below is download link :
download link : 
https://drive.google.com/open?id=1z4FkSB2e2n4Dw13Co3Uwk_Fwfcx2C0-Z

command : 
python create_yolo_caffemodel.py -m tiny-yolo.prototxt -w tiny-yolo-voc-custom_27000.weights -o tiny-yolo.caffemodel

requirement :  python 3.5 , need build caffe first and specify path or copy python dir. to /example

**Comment by HKLee2040** [comment]
Thanks for your reply.   I will try it.
