### ISSUE TITLE
yolo_v2_loss layer

### ISSUE THREAD

**Issue by HKLee2040** [eric612/Caffe-YOLOv2-Windows#5]
Can you show me a prototxt example about how to set yolo_v2_loss layer parameters?

**Comment by eric612** [comment]
I replace the ssd loss layer to yolo_v2_loss_layer at my mobilenet-SSD project and it's works fine
https://github.com/eric612/MobileNet-SSD-linux 

You can reference the parameter of region loss layer at the end of prototxt 
And if have time I'll fix bugs of this project
